from tkinter import *
import os, sys
root = Tk()
mine_image = PhotoImage(file=r"" + os.getcwd() + "\mine.png")
blank_image = PhotoImage(file=r"" + os.getcwd() + "\_blank.png")
zero_image = PhotoImage(file=r"" + os.getcwd() + "\_darkGrey.png")
one_image = PhotoImage(file=r"" + os.getcwd() + "\_one.png")
two_image = PhotoImage(file=r"" + os.getcwd() + "\_two.png")
three_image = PhotoImage(file=r"" + os.getcwd() + "\_three.png")
gridFrame = Frame(root).grid(row=0,column=0)
def mine(button_reference):
 globals()[button_reference].config(image=mine_image)
 print("bum")
def safe(value, button_reference):
 if(value == "0"):
     print("0")
     print(button_reference)
     globals()[button_reference].config(image=zero_image)
 elif(value == "1"):
     print("1")
     print(button_reference)
     globals()[button_reference].config(image=one_image)
 elif((value == "2")):
     print("2")
     print(button_reference)
     globals()[button_reference].config(image=two_image)
 elif((value == "3")):
     print("3")
     print(button_reference)
     globals()[button_reference].config(image=three_image)
 elif((value == "4")):
     print("4")
     print(button_reference)
     globals()[button_reference].config(image=three_image)
 elif((value == "5")):
     print("5")
     print(button_reference)
     globals()[button_reference].config(image=three_image)
 elif((value == "6")):
     print("6")
     print(button_reference)
     globals()[button_reference].config(image=three_image)
 elif((value == "7")):
     print("7")
     print(button_reference)
     globals()[button_reference].config(image=three_image)
 elif((value == "8")):
     print("8")
     print(button_reference)
     globals()[button_reference].config(image=three_image)
button_mine_0 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_0.grid(row=0,column=4)
button_mine_0.config(command = lambda: mine("button_mine_0"))
button_mine_1 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_1.grid(row=2,column=6)
button_mine_1.config(command = lambda: mine("button_mine_1"))
button_mine_2 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_2.grid(row=1,column=6)
button_mine_2.config(command = lambda: mine("button_mine_2"))
button_mine_3 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_3.grid(row=0,column=9)
button_mine_3.config(command = lambda: mine("button_mine_3"))
button_mine_4 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_4.grid(row=5,column=0)
button_mine_4.config(command = lambda: mine("button_mine_4"))
button_mine_5 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_5.grid(row=5,column=2)
button_mine_5.config(command = lambda: mine("button_mine_5"))
button_mine_6 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_6.grid(row=7,column=7)
button_mine_6.config(command = lambda: mine("button_mine_6"))
button_mine_7 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_7.grid(row=2,column=1)
button_mine_7.config(command = lambda: mine("button_mine_7"))
button_mine_8 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_8.grid(row=0,column=9)
button_mine_8.config(command = lambda: mine("button_mine_8"))
button_mine_9 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_9.grid(row=8,column=9)
button_mine_9.config(command = lambda: mine("button_mine_9"))
button_mine_10 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_10.grid(row=7,column=8)
button_mine_10.config(command = lambda: mine("button_mine_10"))
button_mine_11 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_11.grid(row=9,column=1)
button_mine_11.config(command = lambda: mine("button_mine_11"))
button_mine_12 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_12.grid(row=2,column=0)
button_mine_12.config(command = lambda: mine("button_mine_12"))
button_mine_13 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_13.grid(row=3,column=0)
button_mine_13.config(command = lambda: mine("button_mine_13"))
button_mine_14 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_14.grid(row=3,column=1)
button_mine_14.config(command = lambda: mine("button_mine_14"))
button_mine_15 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_15.grid(row=4,column=1)
button_mine_15.config(command = lambda: mine("button_mine_15"))
button_mine_16 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_16.grid(row=8,column=7)
button_mine_16.config(command = lambda: mine("button_mine_16"))
button_mine_17 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_17.grid(row=4,column=0)
button_mine_17.config(command = lambda: mine("button_mine_17"))
button_mine_18 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_18.grid(row=1,column=1)
button_mine_18.config(command = lambda: mine("button_mine_18"))
button_mine_19 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_19.grid(row=3,column=5)
button_mine_19.config(command = lambda: mine("button_mine_19"))
button_0 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_0.grid(row=0,column=0)
button_1 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_1.grid(row=0,column=1)
button_2 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_2.grid(row=0,column=2)
button_3 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_3.grid(row=0,column=3)
button_5 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_5.grid(row=0,column=5)
button_6 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_6.grid(row=0,column=6)
button_7 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_7.grid(row=0,column=7)
button_8 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_8.grid(row=0,column=8)
button_10 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_10.grid(row=1,column=0)
button_12 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_12.grid(row=1,column=2)
button_13 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_13.grid(row=1,column=3)
button_14 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_14.grid(row=1,column=4)
button_15 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_15.grid(row=1,column=5)
button_17 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_17.grid(row=1,column=7)
button_18 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_18.grid(row=1,column=8)
button_19 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_19.grid(row=1,column=9)
button_22 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_22.grid(row=2,column=2)
button_23 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_23.grid(row=2,column=3)
button_24 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_24.grid(row=2,column=4)
button_25 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_25.grid(row=2,column=5)
button_27 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_27.grid(row=2,column=7)
button_28 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_28.grid(row=2,column=8)
button_29 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_29.grid(row=2,column=9)
button_32 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_32.grid(row=3,column=2)
button_33 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_33.grid(row=3,column=3)
button_34 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_34.grid(row=3,column=4)
button_36 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_36.grid(row=3,column=6)
button_37 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_37.grid(row=3,column=7)
button_38 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_38.grid(row=3,column=8)
button_39 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_39.grid(row=3,column=9)
button_42 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_42.grid(row=4,column=2)
button_43 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_43.grid(row=4,column=3)
button_44 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_44.grid(row=4,column=4)
button_45 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_45.grid(row=4,column=5)
button_46 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_46.grid(row=4,column=6)
button_47 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_47.grid(row=4,column=7)
button_48 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_48.grid(row=4,column=8)
button_49 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_49.grid(row=4,column=9)
button_51 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_51.grid(row=5,column=1)
button_53 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_53.grid(row=5,column=3)
button_54 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_54.grid(row=5,column=4)
button_55 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_55.grid(row=5,column=5)
button_56 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_56.grid(row=5,column=6)
button_57 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_57.grid(row=5,column=7)
button_58 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_58.grid(row=5,column=8)
button_59 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_59.grid(row=5,column=9)
button_60 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_60.grid(row=6,column=0)
button_61 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_61.grid(row=6,column=1)
button_62 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_62.grid(row=6,column=2)
button_63 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_63.grid(row=6,column=3)
button_64 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_64.grid(row=6,column=4)
button_65 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_65.grid(row=6,column=5)
button_66 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_66.grid(row=6,column=6)
button_67 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_67.grid(row=6,column=7)
button_68 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_68.grid(row=6,column=8)
button_69 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_69.grid(row=6,column=9)
button_70 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_70.grid(row=7,column=0)
button_71 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_71.grid(row=7,column=1)
button_72 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_72.grid(row=7,column=2)
button_73 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_73.grid(row=7,column=3)
button_74 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_74.grid(row=7,column=4)
button_75 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_75.grid(row=7,column=5)
button_76 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_76.grid(row=7,column=6)
button_79 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_79.grid(row=7,column=9)
button_80 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_80.grid(row=8,column=0)
button_81 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_81.grid(row=8,column=1)
button_82 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_82.grid(row=8,column=2)
button_83 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_83.grid(row=8,column=3)
button_84 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_84.grid(row=8,column=4)
button_85 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_85.grid(row=8,column=5)
button_86 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_86.grid(row=8,column=6)
button_88 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_88.grid(row=8,column=8)
button_90 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_90.grid(row=9,column=0)
button_92 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_92.grid(row=9,column=2)
button_93 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_93.grid(row=9,column=3)
button_94 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_94.grid(row=9,column=4)
button_95 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_95.grid(row=9,column=5)
button_96 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_96.grid(row=9,column=6)
button_97 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_97.grid(row=9,column=7)
button_98 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_98.grid(row=9,column=8)
button_99 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_99.grid(row=9,column=9)
button_0.config(command = lambda: safe("1", "button_0"))
button_1.config(command = lambda: safe("1", "button_1"))
button_2.config(command = lambda: safe("1", "button_2"))
button_3.config(command = lambda: safe("1", "button_3"))
button_5.config(command = lambda: safe("2", "button_5"))
button_6.config(command = lambda: safe("1", "button_6"))
button_7.config(command = lambda: safe("1", "button_7"))
button_8.config(command = lambda: safe("2", "button_8"))
button_10.config(command = lambda: safe("3", "button_10"))
button_12.config(command = lambda: safe("2", "button_12"))
button_13.config(command = lambda: safe("1", "button_13"))
button_14.config(command = lambda: safe("1", "button_14"))
button_15.config(command = lambda: safe("3", "button_15"))
button_17.config(command = lambda: safe("2", "button_17"))
button_18.config(command = lambda: safe("2", "button_18"))
button_19.config(command = lambda: safe("2", "button_19"))
button_22.config(command = lambda: safe("3", "button_22"))
button_23.config(command = lambda: safe("0", "button_23"))
button_24.config(command = lambda: safe("1", "button_24"))
button_25.config(command = lambda: safe("3", "button_25"))
button_27.config(command = lambda: safe("2", "button_27"))
button_28.config(command = lambda: safe("0", "button_28"))
button_29.config(command = lambda: safe("0", "button_29"))
button_32.config(command = lambda: safe("3", "button_32"))
button_33.config(command = lambda: safe("0", "button_33"))
button_34.config(command = lambda: safe("1", "button_34"))
button_36.config(command = lambda: safe("2", "button_36"))
button_37.config(command = lambda: safe("1", "button_37"))
button_38.config(command = lambda: safe("0", "button_38"))
button_39.config(command = lambda: safe("0", "button_39"))
button_42.config(command = lambda: safe("3", "button_42"))
button_43.config(command = lambda: safe("1", "button_43"))
button_44.config(command = lambda: safe("1", "button_44"))
button_45.config(command = lambda: safe("1", "button_45"))
button_46.config(command = lambda: safe("1", "button_46"))
button_47.config(command = lambda: safe("0", "button_47"))
button_48.config(command = lambda: safe("0", "button_48"))
button_49.config(command = lambda: safe("0", "button_49"))
button_51.config(command = lambda: safe("4", "button_51"))
button_53.config(command = lambda: safe("1", "button_53"))
button_54.config(command = lambda: safe("0", "button_54"))
button_55.config(command = lambda: safe("0", "button_55"))
button_56.config(command = lambda: safe("0", "button_56"))
button_57.config(command = lambda: safe("0", "button_57"))
button_58.config(command = lambda: safe("0", "button_58"))
button_59.config(command = lambda: safe("0", "button_59"))
button_60.config(command = lambda: safe("1", "button_60"))
button_61.config(command = lambda: safe("2", "button_61"))
button_62.config(command = lambda: safe("1", "button_62"))
button_63.config(command = lambda: safe("1", "button_63"))
button_64.config(command = lambda: safe("0", "button_64"))
button_65.config(command = lambda: safe("0", "button_65"))
button_66.config(command = lambda: safe("1", "button_66"))
button_67.config(command = lambda: safe("2", "button_67"))
button_68.config(command = lambda: safe("2", "button_68"))
button_69.config(command = lambda: safe("1", "button_69"))
button_70.config(command = lambda: safe("0", "button_70"))
button_71.config(command = lambda: safe("0", "button_71"))
button_72.config(command = lambda: safe("0", "button_72"))
button_73.config(command = lambda: safe("0", "button_73"))
button_74.config(command = lambda: safe("0", "button_74"))
button_75.config(command = lambda: safe("0", "button_75"))
button_76.config(command = lambda: safe("2", "button_76"))
button_79.config(command = lambda: safe("2", "button_79"))
button_80.config(command = lambda: safe("1", "button_80"))
button_81.config(command = lambda: safe("1", "button_81"))
button_82.config(command = lambda: safe("1", "button_82"))
button_83.config(command = lambda: safe("0", "button_83"))
button_84.config(command = lambda: safe("0", "button_84"))
button_85.config(command = lambda: safe("0", "button_85"))
button_86.config(command = lambda: safe("2", "button_86"))
button_88.config(command = lambda: safe("4", "button_88"))
button_90.config(command = lambda: safe("1", "button_90"))
button_92.config(command = lambda: safe("1", "button_92"))
button_93.config(command = lambda: safe("0", "button_93"))
button_94.config(command = lambda: safe("0", "button_94"))
button_95.config(command = lambda: safe("0", "button_95"))
button_96.config(command = lambda: safe("1", "button_96"))
button_97.config(command = lambda: safe("1", "button_97"))
button_98.config(command = lambda: safe("2", "button_98"))
button_99.config(command = lambda: safe("1", "button_99"))
root.mainloop()