from tkinter import *
import os, sys
root = Tk()
mine_image = PhotoImage(file=r"" + os.getcwd() + "\mine.png")
blank_image = PhotoImage(file=r"" + os.getcwd() + "\_blank.png")
zero_image = PhotoImage(file=r"" + os.getcwd() + "\_darkGrey.png")
one_image = PhotoImage(file=r"" + os.getcwd() + "\_one.png")
two_image = PhotoImage(file=r"" + os.getcwd() + "\_two.png")
three_image = PhotoImage(file=r"" + os.getcwd() + "\_three.png")
four_image = PhotoImage(file=r"" + os.getcwd() + "\_four.png")
five_image = PhotoImage(file=r"" + os.getcwd() + "\_five.png")
six_image = PhotoImage(file=r"" + os.getcwd() + "\_six.png")
seven_image = PhotoImage(file=r"" + os.getcwd() + "\_seven.png")
eight_image = PhotoImage(file=r"" + os.getcwd() + "\_eight.png")
gridFrame = Frame(root).grid(row=0,column=0)
def mine(button_reference):
 globals()[button_reference].config(image=mine_image)
 print("bum")
def safe(value, button_reference):
 if(value == "0"):
     print("0")
     print(button_reference)
     globals()[button_reference].config(image=zero_image)
 elif(value == "1"):
     print("1")
     print(button_reference)
     globals()[button_reference].config(image=one_image)
 elif((value == "2")):
     print("2")
     print(button_reference)
     globals()[button_reference].config(image=two_image)
 elif((value == "3")):
     print("3")
     print(button_reference)
     globals()[button_reference].config(image=three_image)
 elif((value == "4")):
     print("4")
     print(button_reference)
     globals()[button_reference].config(image=four_image)
 elif((value == "5")):
     print("5")
     print(button_reference)
     globals()[button_reference].config(image=five_image)
 elif((value == "6")):
     print("6")
     print(button_reference)
     globals()[button_reference].config(image=six_image)
 elif((value == "7")):
     print("7")
     print(button_reference)
     globals()[button_reference].config(image=seven_image)
 elif((value == "8")):
     print("8")
     print(button_reference)
     globals()[button_reference].config(image=eight_image)
button_mine_0 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_0.grid(row=0,column=0)
button_mine_0.config(command = lambda: mine("button_mine_0"))
button_mine_1 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_1.grid(row=0,column=0)
button_mine_1.config(command = lambda: mine("button_mine_1"))
button_mine_2 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_2.grid(row=0,column=0)
button_mine_2.config(command = lambda: mine("button_mine_2"))
button_mine_3 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_3.grid(row=0,column=0)
button_mine_3.config(command = lambda: mine("button_mine_3"))
button_mine_4 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_4.grid(row=0,column=0)
button_mine_4.config(command = lambda: mine("button_mine_4"))
button_mine_5 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_5.grid(row=0,column=0)
button_mine_5.config(command = lambda: mine("button_mine_5"))
button_mine_6 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_6.grid(row=0,column=0)
button_mine_6.config(command = lambda: mine("button_mine_6"))
button_mine_7 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_7.grid(row=0,column=0)
button_mine_7.config(command = lambda: mine("button_mine_7"))
button_mine_8 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_8.grid(row=0,column=0)
button_mine_8.config(command = lambda: mine("button_mine_8"))
button_mine_9 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_9.grid(row=0,column=0)
button_mine_9.config(command = lambda: mine("button_mine_9"))
button_mine_10 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_10.grid(row=0,column=0)
button_mine_10.config(command = lambda: mine("button_mine_10"))
button_mine_11 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_11.grid(row=0,column=0)
button_mine_11.config(command = lambda: mine("button_mine_11"))
button_mine_12 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_12.grid(row=0,column=0)
button_mine_12.config(command = lambda: mine("button_mine_12"))
button_mine_13 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_13.grid(row=0,column=0)
button_mine_13.config(command = lambda: mine("button_mine_13"))
button_mine_14 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_14.grid(row=0,column=0)
button_mine_14.config(command = lambda: mine("button_mine_14"))
button_mine_15 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_15.grid(row=0,column=0)
button_mine_15.config(command = lambda: mine("button_mine_15"))
button_mine_16 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_16.grid(row=0,column=0)
button_mine_16.config(command = lambda: mine("button_mine_16"))
button_mine_17 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_17.grid(row=0,column=0)
button_mine_17.config(command = lambda: mine("button_mine_17"))
button_mine_18 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_18.grid(row=0,column=0)
button_mine_18.config(command = lambda: mine("button_mine_18"))
button_mine_19 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_19.grid(row=0,column=0)
button_mine_19.config(command = lambda: mine("button_mine_19"))
button_mine_20 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_20.grid(row=0,column=0)
button_mine_20.config(command = lambda: mine("button_mine_20"))
button_mine_21 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_21.grid(row=0,column=0)
button_mine_21.config(command = lambda: mine("button_mine_21"))
button_mine_22 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_22.grid(row=0,column=0)
button_mine_22.config(command = lambda: mine("button_mine_22"))
button_mine_23 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_23.grid(row=0,column=0)
button_mine_23.config(command = lambda: mine("button_mine_23"))
button_mine_24 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_24.grid(row=0,column=0)
button_mine_24.config(command = lambda: mine("button_mine_24"))
button_mine_25 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_25.grid(row=0,column=0)
button_mine_25.config(command = lambda: mine("button_mine_25"))
button_mine_26 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_26.grid(row=0,column=0)
button_mine_26.config(command = lambda: mine("button_mine_26"))
button_mine_27 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_27.grid(row=0,column=0)
button_mine_27.config(command = lambda: mine("button_mine_27"))
button_mine_28 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_28.grid(row=0,column=0)
button_mine_28.config(command = lambda: mine("button_mine_28"))
button_mine_29 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_29.grid(row=0,column=0)
button_mine_29.config(command = lambda: mine("button_mine_29"))
button_mine_30 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_30.grid(row=0,column=0)
button_mine_30.config(command = lambda: mine("button_mine_30"))
button_mine_31 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_31.grid(row=0,column=0)
button_mine_31.config(command = lambda: mine("button_mine_31"))
button_mine_32 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_32.grid(row=0,column=0)
button_mine_32.config(command = lambda: mine("button_mine_32"))
button_mine_33 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_33.grid(row=0,column=0)
button_mine_33.config(command = lambda: mine("button_mine_33"))
button_mine_34 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_34.grid(row=0,column=0)
button_mine_34.config(command = lambda: mine("button_mine_34"))
button_mine_35 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_35.grid(row=0,column=0)
button_mine_35.config(command = lambda: mine("button_mine_35"))
button_mine_36 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_36.grid(row=0,column=0)
button_mine_36.config(command = lambda: mine("button_mine_36"))
button_mine_37 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_37.grid(row=0,column=0)
button_mine_37.config(command = lambda: mine("button_mine_37"))
button_mine_38 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_38.grid(row=0,column=0)
button_mine_38.config(command = lambda: mine("button_mine_38"))
button_mine_39 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_39.grid(row=0,column=0)
button_mine_39.config(command = lambda: mine("button_mine_39"))
button_mine_40 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_40.grid(row=0,column=0)
button_mine_40.config(command = lambda: mine("button_mine_40"))
button_mine_41 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_41.grid(row=0,column=0)
button_mine_41.config(command = lambda: mine("button_mine_41"))
button_mine_42 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_42.grid(row=0,column=0)
button_mine_42.config(command = lambda: mine("button_mine_42"))
button_mine_43 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_43.grid(row=0,column=0)
button_mine_43.config(command = lambda: mine("button_mine_43"))
button_mine_44 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_44.grid(row=0,column=0)
button_mine_44.config(command = lambda: mine("button_mine_44"))
button_mine_45 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_45.grid(row=0,column=0)
button_mine_45.config(command = lambda: mine("button_mine_45"))
button_mine_46 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_46.grid(row=0,column=0)
button_mine_46.config(command = lambda: mine("button_mine_46"))
button_mine_47 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_47.grid(row=0,column=0)
button_mine_47.config(command = lambda: mine("button_mine_47"))
button_mine_48 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_48.grid(row=0,column=0)
button_mine_48.config(command = lambda: mine("button_mine_48"))
button_mine_49 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_49.grid(row=0,column=0)
button_mine_49.config(command = lambda: mine("button_mine_49"))
button_mine_50 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_50.grid(row=0,column=0)
button_mine_50.config(command = lambda: mine("button_mine_50"))
button_mine_51 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_51.grid(row=0,column=0)
button_mine_51.config(command = lambda: mine("button_mine_51"))
button_mine_52 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_52.grid(row=0,column=0)
button_mine_52.config(command = lambda: mine("button_mine_52"))
button_mine_53 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_53.grid(row=0,column=0)
button_mine_53.config(command = lambda: mine("button_mine_53"))
button_mine_54 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_54.grid(row=0,column=0)
button_mine_54.config(command = lambda: mine("button_mine_54"))
button_mine_55 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_55.grid(row=0,column=0)
button_mine_55.config(command = lambda: mine("button_mine_55"))
button_mine_56 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_56.grid(row=0,column=0)
button_mine_56.config(command = lambda: mine("button_mine_56"))
button_mine_57 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_57.grid(row=0,column=0)
button_mine_57.config(command = lambda: mine("button_mine_57"))
button_mine_58 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_58.grid(row=0,column=0)
button_mine_58.config(command = lambda: mine("button_mine_58"))
button_mine_59 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_59.grid(row=0,column=0)
button_mine_59.config(command = lambda: mine("button_mine_59"))
button_mine_60 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_60.grid(row=0,column=0)
button_mine_60.config(command = lambda: mine("button_mine_60"))
button_mine_61 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_61.grid(row=0,column=0)
button_mine_61.config(command = lambda: mine("button_mine_61"))
button_mine_62 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_62.grid(row=0,column=0)
button_mine_62.config(command = lambda: mine("button_mine_62"))
button_mine_63 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_63.grid(row=0,column=0)
button_mine_63.config(command = lambda: mine("button_mine_63"))
button_mine_64 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_64.grid(row=0,column=0)
button_mine_64.config(command = lambda: mine("button_mine_64"))
button_mine_65 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_65.grid(row=0,column=0)
button_mine_65.config(command = lambda: mine("button_mine_65"))
button_mine_66 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_66.grid(row=0,column=0)
button_mine_66.config(command = lambda: mine("button_mine_66"))
button_mine_67 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_67.grid(row=0,column=0)
button_mine_67.config(command = lambda: mine("button_mine_67"))
button_mine_68 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_68.grid(row=0,column=0)
button_mine_68.config(command = lambda: mine("button_mine_68"))
button_mine_69 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_69.grid(row=0,column=0)
button_mine_69.config(command = lambda: mine("button_mine_69"))
button_mine_70 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_70.grid(row=0,column=0)
button_mine_70.config(command = lambda: mine("button_mine_70"))
button_mine_71 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_71.grid(row=0,column=0)
button_mine_71.config(command = lambda: mine("button_mine_71"))
button_mine_72 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_72.grid(row=0,column=0)
button_mine_72.config(command = lambda: mine("button_mine_72"))
button_mine_73 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_73.grid(row=0,column=0)
button_mine_73.config(command = lambda: mine("button_mine_73"))
button_mine_74 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_74.grid(row=0,column=0)
button_mine_74.config(command = lambda: mine("button_mine_74"))
button_mine_75 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_75.grid(row=0,column=0)
button_mine_75.config(command = lambda: mine("button_mine_75"))
button_mine_76 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_76.grid(row=0,column=0)
button_mine_76.config(command = lambda: mine("button_mine_76"))
button_mine_77 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_77.grid(row=0,column=0)
button_mine_77.config(command = lambda: mine("button_mine_77"))
button_mine_78 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_78.grid(row=0,column=0)
button_mine_78.config(command = lambda: mine("button_mine_78"))
button_mine_79 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_79.grid(row=0,column=0)
button_mine_79.config(command = lambda: mine("button_mine_79"))
button_mine_80 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_80.grid(row=0,column=0)
button_mine_80.config(command = lambda: mine("button_mine_80"))
button_mine_81 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_81.grid(row=0,column=0)
button_mine_81.config(command = lambda: mine("button_mine_81"))
button_mine_82 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_82.grid(row=0,column=0)
button_mine_82.config(command = lambda: mine("button_mine_82"))
button_mine_83 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_83.grid(row=0,column=0)
button_mine_83.config(command = lambda: mine("button_mine_83"))
button_mine_84 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_84.grid(row=0,column=0)
button_mine_84.config(command = lambda: mine("button_mine_84"))
button_mine_85 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_85.grid(row=0,column=0)
button_mine_85.config(command = lambda: mine("button_mine_85"))
button_mine_86 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_86.grid(row=0,column=0)
button_mine_86.config(command = lambda: mine("button_mine_86"))
button_mine_87 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_87.grid(row=0,column=0)
button_mine_87.config(command = lambda: mine("button_mine_87"))
button_mine_88 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_88.grid(row=0,column=0)
button_mine_88.config(command = lambda: mine("button_mine_88"))
button_mine_89 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_89.grid(row=0,column=0)
button_mine_89.config(command = lambda: mine("button_mine_89"))
button_mine_90 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_90.grid(row=0,column=0)
button_mine_90.config(command = lambda: mine("button_mine_90"))
button_mine_91 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_91.grid(row=0,column=0)
button_mine_91.config(command = lambda: mine("button_mine_91"))
button_mine_92 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_92.grid(row=0,column=0)
button_mine_92.config(command = lambda: mine("button_mine_92"))
button_mine_93 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_93.grid(row=0,column=0)
button_mine_93.config(command = lambda: mine("button_mine_93"))
button_mine_94 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_94.grid(row=0,column=0)
button_mine_94.config(command = lambda: mine("button_mine_94"))
button_mine_95 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_95.grid(row=0,column=0)
button_mine_95.config(command = lambda: mine("button_mine_95"))
button_mine_96 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_96.grid(row=0,column=0)
button_mine_96.config(command = lambda: mine("button_mine_96"))
button_mine_97 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_97.grid(row=0,column=0)
button_mine_97.config(command = lambda: mine("button_mine_97"))
button_mine_98 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_98.grid(row=0,column=0)
button_mine_98.config(command = lambda: mine("button_mine_98"))
button_mine_99 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_mine_99.grid(row=0,column=0)
button_mine_99.config(command = lambda: mine("button_mine_99"))
root.mainloop()