from tkinter import *
from functools import partial
import os, sys
root = Tk()
mine_image = PhotoImage(file=r"" + os.getcwd() + "\mine.png")
blank_image = PhotoImage(file=r"" + os.getcwd() + "\_blank.png")
one_image = PhotoImage(file=r"" + os.getcwd() + "\_one.png")
two_image = PhotoImage(file=r"" + os.getcwd() + "\_two.png")
three_image = PhotoImage(file=r"" + os.getcwd() + "\_three.png")
gridFrame = Frame(root).grid(row=0,column=0)

def mine(button_reference):
    print(globals())
    globals()[button_reference].config(image=mine_image)
    print("bum")

def safe(value, button_reference):
    print(globals())
    if(value == "1"):
        print("1")
        globals()[button_reference].config(image=one_image)
    elif((value == "2")):
        globals()[button_reference].config(image=two_image)
    elif((value == "3")):
        globals()[button_reference].config(image=three_image)


button_1 = Button(gridFrame, width = "40",height = "40", image=blank_image)
button_1.grid(row=0,column=0)
button_1.config(command = lambda: mine("button_1"))
"""
button_2 = Button(gridFrame, width = "40",height = "40",command=partial(mine, "2", "button_2")).grid(row=0,column=1)
button_3 = Button(gridFrame, width = "40",height = "40",command=partial(mine, "3", "button_3")).grid(row=0,column=2)
button_4 = Button(gridFrame, width = "40",height = "40",command=partial(mine, "mine")).grid(row=0,column=3)
button_5 = Button(gridFrame, width = "40",height = "40",command=partial(mine, "1")).grid(row=0,column=4)
button_6 = Button(gridFrame, width = "40",height = "40",command=partial(mine, "2")).grid(row=0,column=5)
button_7 = Button(gridFrame, width = "40",height = "40",command=partial(mine, "3")).grid(row=0,column=6)
button_8 = Button(gridFrame, width = "40",height = "40",command=partial(mine, "mine")).grid(row=0,column=7)
button_9 = Button(gridFrame, width = "40",height = "40",command=partial(mine, "1")).grid(row=0,column=8)
button_10= Button(gridFrame, width = "40",height = "40",command=partial(mine, "2")).grid(row=0,column=9)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=1,column=0)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=1,column=1)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=1,column=2)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=1,column=3)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=1,column=4)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=1,column=5)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=1,column=6)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=1,column=7)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=1,column=8)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=1,column=9)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=2,column=0)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=2,column=1)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=2,column=2)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=2,column=3)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=2,column=4)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=2,column=5)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=2,column=6)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=2,column=7)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=2,column=8)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=2,column=9)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=3,column=0)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=3,column=1)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=3,column=2)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=3,column=3)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=3,column=4)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=3,column=5)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=3,column=6)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=3,column=7)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=3,column=8)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=3,column=9)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=4,column=0)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=4,column=1)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=4,column=2)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=4,column=3)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=4,column=4)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=4,column=5)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=4,column=6)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=4,column=7)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=4,column=8)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=4,column=9)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=5,column=0)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=5,column=1)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=5,column=2)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=5,column=3)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=5,column=4)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=5,column=5)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=5,column=6)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=5,column=7)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=5,column=8)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=5,column=9)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=6,column=0)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=6,column=1)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=6,column=2)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=6,column=3)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=6,column=4)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=6,column=5)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=6,column=6)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=6,column=7)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=6,column=8)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=6,column=9)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=7,column=0)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=7,column=1)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=7,column=2)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=7,column=3)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=7,column=4)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=7,column=5)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=7,column=6)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=7,column=7)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=7,column=8)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=7,column=9)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=8,column=0)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=8,column=1)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=8,column=2)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=8,column=3)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=8,column=4)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=8,column=5)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=8,column=6)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=8,column=7)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=8,column=8)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=9,column=9)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=9,column=0)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=9,column=1)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=9,column=2)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=9,column=3)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=9,column=4)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=9,column=5)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=9,column=6)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=9,column=7)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=9,column=8)
button_ = Button(gridFrame, width = "40",height = "40",command=partial(mine, "ahoj")).grid(row=8,column=9)"""

root.mainloop()